### PR TITLE
Fix Post not Updating [Fixes #1048]

### LINKED ISSUE #1048: Cannot Update the Post inside Talawa-Admin
This issue is related to the issue https://github.com/PalisadoesFoundation/talawa-admin/issues/464

The code changes for the above issue inside Talawa-API will be synced to this issue.

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
The post was not being updated in the Talawa-Admin Panel, since, there was no mutation named "updatePost", and there was no resolver for it.

**Issue Number:**

Fixes #1048 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
Not Required

**Summary**
The post was not being updated in the Talawa-Admin Panel, since, there was no mutation named "updatePost", and there was no resolver for it.

**Does this PR introduce a breaking change?**
No.

**Other information**
No.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
This PR resolves the merge conflicts arrived due to change in typeDefs. PR linked to this is https://github.com/PalisadoesFoundation/talawa-api/pull/1054

File: src/resolvers/Mutation/updatePost.ts [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    throw new errors.NotFoundError(
+      requestContext.translate(POST_NOT_FOUND_MESSAGE),
+      POST_NOT_FOUND_CODE,
+      POST_NOT_FOUND_PARAM
+    );
+  }
+
+  const currentUserIsPostAdmin =
+    post.creator.toString() === context.userId.toString();
+
```
Comment (xoldyckk) [inline src/resolvers/Mutation/updatePost.ts:49]: Post only has a creator not admin. Name it properly to not confuse people.

File: tests/resolvers/Mutation/updatePost.spec.ts [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+        userId: testUser!._id,
+      };
+
+      await updatePostResolver?.({}, args, context);
+    } catch (error: any) {
+      expect(error.message).toEqual(POST_NOT_FOUND_MESSAGE);
+    }
+  });
+
+  it(`throws UnauthorizedError as current user with _id === context.userId is an admin of post with _id === args.id`, async () => {
```
Comment (xoldyckk) [inline tests/resolvers/Mutation/updatePost.spec.ts:66]: This test is useless because catch block never executes. Because testUser is already a creator of of post. Remove this.

**Review by xoldyckk — COMMENTED** [review]
Make the required changes

File: src/resolvers/Mutation/updatePost.ts (hunk 1 above)
Comment (anshgoyalevil) [reply src/resolvers/Mutation/updatePost.ts:49]: Done.

File: tests/resolvers/Mutation/updatePost.spec.ts (hunk 2 above)
Comment (anshgoyalevil) [reply tests/resolvers/Mutation/updatePost.spec.ts]: Done.

**Review by xoldyckk — APPROVED** [review]

**Comment by anshgoyalevil** [comment]
@palisadoes Please take a look at it Sir.

**Review by palisadoes — APPROVED** [review]
