### PR TITLE
fix minor bug: ensure single database connection on server startup

### LINKED ISSUE #2161: Minor bug while starting the server
### Describe the bug
1) The logs on server connection show an error due to incorrect mongo uri used in the `loadPlugin` function.
2) Multiple connections to the database are being made in startup functions.

### To Reproduce

1. Start the server.
2. See the logs.

### Current behavior
current

### Expected behavior
Should only connect to the database once, and show appropriate logs
desired

### Solution
1) Correct the mongo uri in the `loadPlugin` function.
2) Before connecting to the database, check if a connection already exists, if not, then only establish a new connection.

### PR DESCRIPTION
**Pull request by lokeshwar777**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #2161

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No

**Summary**

1. This PR resolves a bug causing server errors due to an incorrect MongoDB URI in the loadPlugin function.
2. It prevents multiple database connections during startup by implementing logic to check for existing connections before establishing a new one.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

File: src/db.ts [hunk 1]
```diff
@@ -3,9 +3,14 @@ import { MONGO_DB_URL } from "./constants";
...
 import { checkReplicaSet } from "./utilities/checkReplicaSet";
 
+let isConnected = false;
 let session!: mongoose.ClientSession;
 
 export const connect = async (dbName?: string): Promise<void> => {
+  if (isConnected) {
+    return;
+  }
+
```
Comment (meetulr) [inline src/db.ts:13]: hey @lokeshwar777 creating a separate variable for checking connection state can't be a good practice, it could cause weird behaviour. Use something like `mongoose.connection.readyState` in the files that are calling the `connect()` functions.

Comment (lokeshwar777) [reply src/db.ts:12]: @meetulr Thanks for the feedback, I have made the changes you have suggested.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@meetulr Comments please

**Comment by meetulr** [comment]
Yes, this is what I had in mind.

@lokeshwar777 I'd be better for the sake of clarity if you added a comment specifying what the check is doing, i.e. we're first checking if a connection already exist, if not, then only we're establishing a new one.

**Comment by palisadoes** [comment]
Please add the check comments so that we can review and merge

**Comment by palisadoes** [comment]
@meetulr PTAL again

**Comment by meetulr** [comment]
Yes this looks good.

**Review by palisadoes — APPROVED** [review]
