### PR TITLE
fixed `docker-compose.dev.yaml` to run admin and api

### LINKED ISSUE #2730: API: Extremely Poor Docker Resource Utilization Efficiency
**Describe the bug**

We run a demonstration instance of Talawa-API on a GoDaddy VPS server running Ubuntu. It has the following resources:

1. 1 core
1. 2 GB of RAM
1. 40 GB of disk

Other information:

1. The demo instance is intended to create an evaluation environment for new GtiHub contributors and users alike as they decide to use Talawa. The DB of the demo instance gets reset every day.
2. Talawa API runs natively on this VPS server with acceptable performance with one user. The load average is approximately 1, which is the target value for a system with only 1 core.
3. When Talawa API runs on the server using docker. The load average reaches 130, the swap process is the top CPU resource user. The system is so overloaded that only one ssh session at a time is achievable.

The purpose of this issue is to find ways to tune all Talawa-API Dockerfile and app configurations to lower its CPU and RAM utilization by at least 75% 

1. With the current Docker performance very few developers or end users will want to try Talawa themselves.
2. This has been a recurring issue with Talawa API. The poor performance threatens the success of our current MongoDB based MVP.

**To Reproduce**

1. Run Talawa-API on a system
2. See excessive resource utilization

**Expected behavior**

1. Acceptable usage information such that it can run easily on a mid-range laptop without impacting its performance

**Actual behavior**

1. Poor performance

**Screenshots**

image

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by VanshikaSabharwal**
**What kind of change does this PR introduce?**

bugfix, feature

**Issue Number:**

Fixes #2730 

**Snapshots/Videos:**

Screenshot from 2025-02-14 20-29-34

**If relevant, did you update the documentation?**

**Summary**
- I updated the URL for mongo db connection in `docker-compose.dev.yaml` and `docker-compose.prod.yaml`
- I added the access and refresh token in `docker-compose.dev.yaml` in order to resolver below error. 
  Previous Error:
Screenshot from 2025-02-14 19-37-13
Screenshot from 2025-02-14 19-51-01
Screenshot from 2025-02-14 19-38-45

**Does this PR introduce a breaking change?**

### CodeRabbit AI Review
- [x] I have reviewed and addressed all critical issues flagged by CodeRabbit AI
- [x] I have implemented or provided justification for each non-critical suggestion
- [x] I have documented my reasoning in the PR comments where CodeRabbit AI suggestions were not implemented

### Test Coverage
- [x] I have written tests for all new changes/features
- [x] I have verified that test coverage meets or exceeds 95%
- [x] I have run the test suite locally and all tests pass

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **Chores**
  - Updated the development service configuration to connect to the new database.
  - Revised the production service configuration for consistent and reliable database connectivity.
  - Enhanced the data import script to generate and export new access and refresh token secrets.
  - Added new environment variables for improved configuration management.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Is there a way to dynamically create the tokens versus hard coding them?
2. Why didn't you create tokens for prod?

**Comment by VanshikaSabharwal** [comment]
Okay i am updating it.

**Comment by palisadoes** [comment]
Could this work?https://stackoverflow.com/questions/63501025/how-to-set-environment-variables-dynamically-by-script-in-dockerfile

**Comment by prayanshchh** [comment]
@VanshikaSabharwal my previous PR changed the db in loadsampledata to talawa-dev, you have changed the URL to api.

**Comment by VanshikaSabharwal** [comment]
@prayanshchh but i am able to login after i updated it. There is no error

**Comment by VanshikaSabharwal** [comment]
@prayanshchh I am setting it back to `api` because the data is in `talawa-api` not `talawa-dev` . And the test is also failing because of it.

**Comment by VanshikaSabharwal** [comment]
it's `api` only in code
image

**Comment by palisadoes** [comment]
1. @VanshikaSabharwal  There are 2 new references to `talawa-dev` in `tests/utilities/loadSampleData.spec.ts`
2. @prayanshchh your PR was merged with the failing tests by accident. PTAL
    - https://github.com/PalisadoesFoundation/talawa-api/actions/runs/13332160820/job/37238777649

**Comment by VanshikaSabharwal** [comment]
Yes @palisadoes I updated it.

File: src/utilities/loadSampleData.ts [hunk 1]
```diff
@@ -95,7 +95,7 @@ async function resetDatabase(): Promise<void> {
 async function insertCollections(collections: string[]): Promise<void> {
   try {
     // Connect to MongoDB database
-    await connect("talawa-dev");
+    await connect("talawa-api");
```
Comment (palisadoes) [inline src/utilities/loadSampleData.ts:98]: Using `talawa-dev` fixed the cloud server. Why was this reverted?

File: src/utilities/loadSampleData.ts [hunk 2]
```diff
@@ -160,7 +160,7 @@ async function insertCollections(collections: string[]): Promise<void> {
 async function checkCountAfterImport(): Promise<void> {
   try {
     // Connect to MongoDB database
-    await connect("talawa-dev");
+    await connect("talawa-api");
```
Comment (palisadoes) [inline src/utilities/loadSampleData.ts:163]: Using `talawa-dev` fixed the cloud server. Why was this reverted?

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Using `talawa-dev` fixed the cloud server. 
2. The test needs to be updated

**Comment by prayanshchh** [comment]
> 1. @VanshikaSabharwal  There are 2 new references to `talawa-dev` in `tests/utilities/loadSampleData.spec.ts`
> 2. @prayanshchh your PR was merged with the failing tests by accident. PTAL
>    
>    * [Fix data importation #3212](https://github.com/PalisadoesFoundation/talawa-api/pull/3212)
>    * https://github.com/PalisadoesFoundation/talawa-api/actions/runs/13332160820/job/37238777649
>      image

yes I noticed it, I have fixed it locally, we just have to change the db name in test file, and it would pass the test, I did this in my branch, but my PR was merged before that

image

File: docker-compose.dev.yaml [hunk 3]
```diff
@@ -75,11 +75,14 @@ services:
         condition: service_started
       minio:
         condition: service_started
+    env_file:
+     - .env
     environment:
-      - MONGO_DB_URL=mongodb://mongo:27017/talawa-dev?replicaSet=rs0
+      - MONGO_DB_URL=mongodb://mongo:27017/talawa-api?replicaSet=rs0
```
Comment (palisadoes) [inline docker-compose.dev.yaml:81]: This should be `dev` for the `dev` environment

File: docker-compose.prod.yaml [hunk 4]
```diff
@@ -75,8 +75,10 @@ services:
         condition: service_started
       minio:
         condition: service_started
+    env_file:
+     - .env
     environment:
-      - MONGO_DB_URL=mongodb://mongo:27017/talawa-dev?replicaSet=rs0
+      - MONGO_DB_URL=mongodb://mongo:27017/talawa-api?replicaSet=rs0
```
Comment (palisadoes) [inline docker-compose.prod.yaml:81]: This looks OK

**Review by palisadoes — CHANGES_REQUESTED** [review]
see comments

File: src/utilities/loadSampleData.ts (hunk 2 above)
Comment (VanshikaSabharwal) [reply src/utilities/loadSampleData.ts:163]: @palisadoes because `talawa-api` has all data not `talawa-dev`  which is why we were not able to login when it was `talawa-dev` that is why i updated it to `talawa-api` that is when login/signup was possible


Screenshot from 2025-02-14 19-33-09
IMG_20250214_192856

File: docker-compose.prod.yaml [hunk 5]
```diff
@@ -75,8 +75,10 @@ services:
         condition: service_started
       minio:
         condition: service_started
+    env_file:
+     - .env
```
Comment (palisadoes) [inline docker-compose.prod.yaml:79]: Please remove. This will cause docker to fail if there is no `.env` file, which is already happening

File: docker-compose.dev.yaml [hunk 6]
```diff
@@ -75,11 +75,14 @@ services:
         condition: service_started
       minio:
         condition: service_started
+    env_file:
+     - .env
```
Comment (palisadoes) [inline docker-compose.dev.yaml:79]: Please remove. This will cause docker to fail if there is no `.env` file, which is already happening

**Review by palisadoes — CHANGES_REQUESTED** [review]
See comments

File: docker-compose.dev.yaml (hunk 6 above)
Comment (VanshikaSabharwal) [reply docker-compose.dev.yaml:79]: yes

File: docker-compose.dev.yaml [hunk 7]
```diff
@@ -76,10 +76,16 @@ services:
...
     environment:
-      - MONGO_DB_URL=mongodb://mongo:27017/talawa-dev?replicaSet=rs0
+      - MONGO_DB_URL=mongodb://mongo:27017/talawa-api?replicaSet=rs0
       - NODE_ENV=development
       - REDIS_HOST=redis-stack-server
       - REDIS_PORT=6379
+      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
+      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
+      - MINIO_ROOT_USER=$(MINIO_ROOT_USER)
+      - MINIO_ROOT_PASSWORD=$(MINIO_ROOT_PASSWORD)
```
[the remark this answers is not in the document]
Comment (VanshikaSabharwal) [reply docker-compose.dev.yaml:86]: yes i did it thank you

**Comment by VanshikaSabharwal** [comment]
@coderabbitai full review

**Comment by VanshikaSabharwal** [comment]
@coderabbitai full review

**Review by palisadoes — APPROVED** [review]
