### PR TITLE
Returning Empty Array Instead of Throwing Error

### LINKED ISSUE #1260: Users query returns error when no user match filters
**Describe the bug**

**To Reproduce**

1. Run Talawa API and open Playground
2. Run the `Users` query with filters that don't match any user
3. It returns an error
4. Instead of an empty array

**Expected behavior**

- When no filters match, the query should return an empty array
- This is useful when filtering all the users in the `Organization People` page
- And the filters don't match
- Like how the `organizationsConnection` query works

**Actual behavior**

- It returns 422 error which caused frontend to fail

**Screenshots**

`Users` Query -

Screenshot 2023-04-06 at 7 25 30 PM

`organizationsConnection` Query -

Screenshot 2023-04-06 at 7 26 13 PM

**Additional details**

I discovered this issue while working on [this](https://github.com/PalisadoesFoundation/talawa-admin/issues/730) issue in Talawa Admin

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by prathamesh-mutkure**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #1260 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Screenshot 2023-04-06 at 11 04 42 PM

**If relevant, did you update the documentation?**

Not Relevant

**Summary**

- The `Users` Query returned the `UserNotFound` Error when none of the filters matched
- Other queries like the `organizationsConnection` returned an empty array instead
- This created problems in the admin when filtering users in the Organization People page
- And the filters didn't match any user
- I've fixed this issue to return an empty array instead

**Does this PR introduce a breaking change?**

No

**Other information**

This issue will help solving https://github.com/PalisadoesFoundation/talawa-admin/issues/730

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

File: src/resolvers/Query/users.ts [hunk 1]
```diff
@@ -45,24 +45,17 @@ export const users: QueryResolvers["users"] = async (
...
-    throw new errors.NotFoundError(
-      requestContext.translate(USER_NOT_FOUND_ERROR.MESSAGE),
-      USER_NOT_FOUND_ERROR.CODE,
-      USER_NOT_FOUND_ERROR.PARAM
-    );
-  } else
-    return users.map((user) => {
-      const { userType } = queryUser;
+  return users.map((user) => {
+    const { userType } = queryUser;
```
Comment (xoldyckk) [inline src/resolvers/Query/users.ts:49]: Change variable name from `queryUser` to `currentUser`

File: tests/resolvers/Query/users.spec.ts [hunk 2]
```diff
@@ -80,34 +76,24 @@ describe("resolvers -> Query -> users", () => {
...
-    const { requestContext } = await import("../../../src/libraries");
+    const testUser = await createTestUser();
 
-    const spy = vi
-      .spyOn(requestContext, "translate")
-      .mockImplementationOnce((message) => `Translated ${message}`);
+    const args: QueryUsersArgs = {
+      orderBy: null,
+      where: {
+        id: testObjectId as unknown as string,
```
Comment (xoldyckk) [inline tests/resolvers/Query/users.spec.ts:84]: Idk who wrote these `as unknown as string` annotations. Remove them and convert the objectIds to string before passing them into resolvers, whether in arguments, or context.

**Comment by prathamesh-mutkure** [comment]
@xoldyckk done

**Review by xoldyckk — COMMENTED** [review]
Why are constants being mocked?

@prathamesh-mutkure look into it, if there's no use of mocking get rid of the mocks.

**Comment by prathamesh-mutkure** [comment]
Yes, you're right, we don't need to mock constants here as they're not being overwritten in these tests.

@xoldyckk I've removed mocks for constant.

This might be a problem with other test files too, should I create an issue to remove all types of unnecessary mocks?

**Comment by xoldyckk** [comment]
> Yes, you're right, we don't need to mock constants here as they're not being overwritten in these tests.
> 
> @xoldyckk I've removed mocks for constant.
> 
> This might be a problem with other test files too, should I create an issue to remove all types of unnecessary mocks?

sure

**Review by xoldyckk — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]
