### PR TITLE
$pull and promises handled for the the queries in cancelMembershipRequest.ts

### LINKED ISSUE #1315: Use Promise.all to execute multiple queries in parallel and $pull to remove field in cancelMembershipRequest.ts
**Describe the bug**

- Instead of executing each database query sequentially, you can execute them in parallel using Promise.all. This can significantly reduce the total execution time of the function.
- Use $pull to remove the fields

**To Reproduce**

1. start the server locally using the command 'npm run dev'
2. run the query for cancelMembershipRequest

**Expected behavior**
NA

**Actual behavior**
NA

**Screenshots**
Not required

**Additional details**
Not required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by nishant3721**
**What kind of change does this PR introduce?**

Refactoring

**Issue Number:**

Fixes #1315 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Not required

**If relevant, did you update the documentation?**

Not relevant

**Does this PR introduce a breaking change?**

No

**Other information**

Not required

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
Why haven't you added tests to verify this new functionality?

**Comment by nishant3721** [comment]
> Why haven't you added tests to verify this new functionality?

Sir, there is no new functionality added, it is just that I have handled multiple queries promises with Promise.all to aggregate the queries. Also, I have run the test for cancelMemebershipRequest.ts, it has the 100% code coverage.

**Review by palisadoes — DISMISSED** [review]

File: src/resolvers/Mutation/cancelMembershipRequest.ts [hunk 1]
```diff
@@ -60,50 +56,45 @@ export const cancelMembershipRequest: MutationResolvers["cancelMembershipRequest
       );
     }
 
-    const currentUserCreatedMembershipRequest =
-      currentUser._id.toString() === membershipRequest.user.toString();
-
     // Checks whether currentUser is the creator of membershipRequest.
-    if (currentUserCreatedMembershipRequest === false) {
+    if (!(currentUser._id.toString() === membershipRequest.user.toString())) {
```
Comment (xoldyckk) [inline src/resolvers/Mutation/cancelMembershipRequest.ts:60]: use mongoose objectid `.equals()` method for comparision

File: src/resolvers/Mutation/cancelMembershipRequest.ts [hunk 2]
```diff
@@ -60,50 +56,45 @@ export const cancelMembershipRequest: MutationResolvers["cancelMembershipRequest
...
-    await Organization.updateOne(
-      {
-        _id: organization._id,
-      },
-      {
-        $set: {
-          membershipRequests: organization.membershipRequests.filter(
-            (request) => request.toString() !== membershipRequest._id.toString()
-          ),
+    const promises = [
```
Comment (xoldyckk) [inline src/resolvers/Mutation/cancelMembershipRequest.ts:68]: instead of promises, mutations should use transactions

Comment (nishant3721) [reply src/resolvers/Mutation/cancelMembershipRequest.ts:68]: I didn't get it, can you elaborate a little bit sir!?

Comment (nishant3721) [reply src/resolvers/Mutation/cancelMembershipRequest.ts:68]: You mean, aggregate the queries!?

Comment (nishant3721) [reply src/resolvers/Mutation/cancelMembershipRequest.ts:68]: @xoldyckk It requires the DB to be run as a replica set

Comment (palisadoes) [reply src/resolvers/Mutation/cancelMembershipRequest.ts:68]: Wouldn't sending all queries at once be advantageous for connection pooling with the ORM? Your suggestion implies having one query per TCP/IP connection. Pooling would help to reduce the total number of TCP/IP connections to the API while maintaining the query count, by having one TCP/IP connection to handle groups of queries. Does the `Promise.all` make pooling possible?

Comment (anshgoyalevil) [reply src/resolvers/Mutation/cancelMembershipRequest.ts:68]: As @xoldyckk described, using the ```Promise.all``` can affect the database and atomicity wouldn't be maintained. Moreover, it can lead to database failure.

We are sending multiple database requests in Parallel using ```Promise.all``` and this can lead to database failure in case the bandwidth or throughput is low.

We are targeting small organizations too, which might depend upon small server and database instances. They might not support replica sets (cause extra capex) for fail over protection.

Comment (nishant3721) [reply src/resolvers/Mutation/cancelMembershipRequest.ts:68]: @palisadoes @xoldyckk @anshgoyalevil I will it be, as it will have a different implementation from the rest of the talawa-api operation, which doesn't make any sense.

File: src/resolvers/Mutation/cancelMembershipRequest.ts [hunk 3]
```diff
@@ -34,9 +34,10 @@ export const cancelMembershipRequest: MutationResolvers["cancelMembershipRequest
       );
     }
 
-    const organization = await Organization.findOne({
-      _id: membershipRequest.organization,
-    }).lean();
+    const [organization, currentUser] = await Promise.all([
```
Comment (xoldyckk) [inline src/resolvers/Mutation/cancelMembershipRequest.ts:37]: Seperate this one too, to keep the implementation uniform across all resolvers.

**Review by palisadoes — APPROVED** [review]
