### PR TITLE
fixed the structure of env.ts, redefined .env schema  and made some type changes

### LINKED ISSUE #1521: API Startup Error Messages Need Resolving
**Describe the bug**
When starting the API the following error messages are displayed. It doesn't affect operations

```
[0] error 2023-12-20 17:19:16 - Invalid environment variables found in your .env file, check the errors below! {}
[0] Code: invalid_type ~ Path: apiKey ~ Message: Required
Code: invalid_type ~ Path: appId ~ Message: Required
Code: invalid_type ~ Path: messagingSenderId ~ Message: Required
Code: invalid_type ~ Path: projectId ~ Message: Required
Code: invalid_type ~ Path: storageBucket ~ Message: Required
Code: invalid_type ~ Path: iOSapiKey ~ Message: Required
Code: invalid_type ~ Path: iOSappId ~ Message: Required
Code: invalid_type ~ Path: iOSmessagingSenderId ~ Message: Required
Code: invalid_type ~ Path: iOSprojectId ~ Message: Required
Code: invalid_type ~ Path: iOSstorageBucket ~ Message: Required
Code: invalid_type ~ Path: iosClientId ~ Message: Required
Code: invalid_type ~ Path: iosBundleId ~ Message: Required
```

**To Reproduce**
- Start non docker API instance

**Expected behavior**
- No error messages because the root cause is fixed. Suppressing error messages is not an acceptable solution.
- No change to the app's functionality
- All tests pass

**Actual behavior**
- Error messages

**Screenshots**
- N/A

**Additional details**
-N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by adi790uu**
**What kind of change does this PR introduce?**

It fixes the API Startup Error Messages.

**Issue Number:**

Fixes #1521 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Screenshot 2024-01-18 at 7 41 29 PM

**Summary**

When non docker API instance is started, it displayed some error messages related to the .env variables.This PR fixes those problems by redefining the structure of schema.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

File: src/utilities/mailer.ts [hunk 1]
```diff
@@ -20,17 +21,19 @@ export interface InterfaceMailFields {
...
+  mailFields: InterfaceMailFields
+): Promise<SMTPTransport.SentMessageInfo | string> => {
   // Nodemailer configuration
-  let transporter: any;
+  let transporter: Transporter<SMTPTransport.SentMessageInfo>;
 
   // For using custom smtp server
   /* c8 ignore next 12 */
-  if (SMTP_OPTIONS.IS_SMTP === "true") {
+  if (SMTP_OPTIONS.IS_SMTP === true) {
```
Comment (EshaanAgg) [inline src/utilities/mailer.ts:32]:
```suggestion
  if (SMTP_OPTIONS.IS_SMTP) {
```

File: src/utilities/mailer.ts [hunk 2]
```diff
@@ -50,20 +53,23 @@ export const mailer = (mailFields: InterfaceMailFields): Promise<any> => {
   const mailOptions = {
     /* c8 ignore next 6 */
     from:
-      SMTP_OPTIONS.IS_SMTP === "false" || SMTP_OPTIONS.IS_SMTP === undefined
+      SMTP_OPTIONS.IS_SMTP === false || SMTP_OPTIONS.IS_SMTP === undefined
```
Comment (EshaanAgg) [inline src/utilities/mailer.ts:56]:
```suggestion
      !SMTP_OPTIONS.IS_SMTP 
```

**Review by EshaanAgg — CHANGES_REQUESTED** [review]

**Review by EshaanAgg — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]
