### PR TITLE
fix:tags can be added while creating organization

### LINKED ISSUE #853: Not able to add tags in Organization
**Describe the bug**
Cannot add tags in the organization, while creating it.
Getting error

image

**To Reproduce**
Steps to reproduce the behaviour:
1. Create organization through graphql interface

image

**Screenshots**
image

**Additional details**
Due to this issue, the organization cannot be created on frontend

https://github.com/PalisadoesFoundation/talawa-admin/issues/370

https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1672987548733609?thread_ts=1672903169.859759&cid=C01RPC00K0D

### PR DESCRIPTION
**Pull request by VenomFate-619**
**What kind of change does this PR introduce?**
Allowing users to add tag while creating organization

**Issue Number:**

Fixes #853 

**Did you add tests for your changes?**

No 

**Snapshots/Videos:**

image

image

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

**Additional Context**

Made tags required, as it was a necessary field  in frontend

### CODE REVIEW

**Comment by VenomFate-619** [comment]
Should I need to create a test to check if tags are added or not

**Comment by palisadoes** [comment]
> Should I need to create a test to check if tags are added or not

Yes we need to make sure that we test all new code added to the code base

**Comment by xoldyckk** [comment]
@VenomFate-619 Turn `tags: [String]!` to `tags: [String!]!`. You don't want to allow null values inside tags list. It's either an empty list `[ ]` or a list of string values `[ "tag1", "tag2", ... ]`. It should not be `[ null, "tag2", ... ]`. You get the idea.

File: src/lib/typeDefs/organization.ts [hunk 1]
```diff
@@ -39,6 +39,7 @@ export const organization = gql`
     isPublic: Boolean!
     visibleInSearch: Boolean!
     apiUrl: String
+    tags: [String]!
```
Comment (SiddheshKukade) [inline src/lib/typeDefs/organization.ts:42]: change to `tags : [String!] !` as suggested by @xoldyckk

**Comment by palisadoes** [comment]
@VenomFate-619 Please add tests for this so that we don't have this issue again. The code reliability is really important.

**Comment by JamaicanFriedChicken** [comment]
@VenomFate-619 Reminder to add the tests for the tags ~

**Comment by VenomFate-619** [comment]
> @VenomFate-619 Reminder to add the tests for the tags as well as resolve the conflicts ~

Sorry for replying late.
Yup on it.

**Comment by VenomFate-619** [comment]
> # [Codecov](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/875?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> > Merging [#875](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/875?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) ([6a932b7](https://github.com/PalisadoesFoundation/talawa-api/commit/6a932b7d84b82e0e52ec64a97b365d2b52dfa014)) into [develop](https://codecov.io/gh/PalisadoesFoundation/talawa-api/commit/f3681ecc5918f2c46c5f281d681990a5f465214f?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) ([f3681ec](https://github.com/PalisadoesFoundation/talawa-api/commit/f3681ecc5918f2c46c5f281d681990a5f465214f)) will **increase** coverage by `0.08%`.
> > The diff coverage is `n/a`.
> 
> ```diff
> @@             Coverage Diff             @@
> ##           develop     #875      +/-   ##
> ===========================================
> + Coverage    81.17%   81.26%   +0.08%     
> ===========================================
>   Files          168      168              
>   Lines        10086    10086              
>   Branches       855      858       +3     
> ===========================================
> + Hits          8187     8196       +9     
> + Misses        1897     1888       -9     
>   Partials         2        2              
> ```
> 
> [Impacted Files](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/875?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)	Coverage Δ	
> [src/lib/resolvers/Query/users.ts](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/875?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2xpYi9yZXNvbHZlcnMvUXVlcnkvdXNlcnMudHM=)	`100.00% <0.00%> (+2.41%)`	
> mega We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)

I think as coverage is increased no need of fixing this.
If it is needed to get back to the base version, can someone help me with that

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]
